Fix export of CSV.
mt-support/tribe-ext-export-mec-events pull request #5
Opened 2023-08-04 01:00 UTC by stratease

[TEC-4442](https://theeventscalendar.atlassian.net/browse/TEC-4442)

Fix issues with CSV exports for the MEC data. The settings page ID had changed, and was not updated here in it's reference in the export URL.

2023-08-07 17:50 UTC, Camwyn commented on tribe-ext-export-mec-events.php
> +
Does $this->add_required_plugin( 'Tribe__Events__Main' ); (below, line 41, in unedited code) require a TEC version set?

2023-08-07 17:50 UTC, Camwyn commented on tribe-ext-export-mec-events.php
> +		 * @param array  $csv_header    - The name of the columns
```suggestion
		 * @param array  $csv_header    The name of the columns
```

2023-08-11 13:39 UTC, Camwyn requested changes
Couple small wording/format changes. The others are observations for a possible future refactor/reorganization (you can ignore those for the purposes of the review 😉).

2023-08-11 13:39 UTC, Camwyn commented on readme.txt
> +* Compatibility - Setting required The Events Calendar version to 5.15.0. [TEC-4442]
```suggestion
* Compatibility - Setting the required version of The Events Calendar to 5.15.0. [TEC-4442]
```

2023-08-11 13:39 UTC, Camwyn commented on tribe-ext-export-mec-events.php
> +			fputcsv( $fh, $csv_header );
```suggestion
			fputcsv( $fh, $csv_header );
			
```
I added a line break

2023-08-11 13:39 UTC, Camwyn commented on tribe-ext-export-mec-events.php
>  			if ( empty( $_REQUEST['export_events'] ) && empty( $_REQUEST['export_organizers'] ) && empty( $_REQUEST['export_venues'] ) || ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'export_events' ) && ! wp_ve
Not a changed line, but this feels terribly redundant?

2023-08-11 13:39 UTC, Camwyn commented on tribe-ext-export-mec-events.php
>  			if ( empty( $_REQUEST['export_events'] ) && empty( $_REQUEST['export_organizers'] ) && empty( $_REQUEST['export_venues'] ) || ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'export_events' ) && ! wp_ve
...and long 😉

2023-08-11 13:39 UTC, Camwyn commented on readme.txt
> +* Compatibility - Setting required The Events Calendar version to 5.15.0. [TEC-4442]
slightly better wording 😉

2023-08-15 16:42 UTC, stratease commented on tribe-ext-export-mec-events.php
>  			if ( empty( $_REQUEST['export_events'] ) && empty( $_REQUEST['export_organizers'] ) && empty( $_REQUEST['export_venues'] ) || ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'export_events' ) && ! wp_ve
Reads like Shakespeare!

2023-08-16 15:29 UTC, Camwyn approved these changes

2023-08-16 18:10 UTC, merged